Repository base/web, pull requests merged in 2023-10, with the labels that each got.

#42 Add CCA Lite domains to Base Docs CSP.
  apps/base-docs/server.js
Labels: minor, type: bug

#41 Add hardware requirements, snapshots instrux and EBS callout to Node guide
  apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
Labels: type: enhancement

#14 Add landing page for Base Bootcamp
  apps/base-docs/docusaurus.config.js
  apps/web/package.json
  apps/web/pages/bootcamp.tsx
  apps/web/public/images/base-bootcamp-white.png
  apps/web/public/images/bootcamp-background.png
  apps/web/src/components/Bootcamp/Cost.tsx
  apps/web/src/components/Bootcamp/Dates.tsx
  apps/web/src/components/Bootcamp/Faq/FaqSidebar.tsx
  apps/web/src/components/Bootcamp/Faq/QuestionAccordion.tsx
  apps/web/src/components/Bootcamp/Hero.tsx
  apps/web/src/components/Bootcamp/HowItWorks/HowItWorksCard.tsx
  apps/web/src/components/Bootcamp/HowItWorks/index.tsx
  apps/web/src/components/Bootcamp/WhatsIncluded.tsx
  apps/web/src/components/Layout/Nav/Nav.tsx
  apps/web/src/components/Logo/Logo.tsx
  apps/web/tailwind.config.js
  package-lock.json
  yarn.lock
Labels: type: enhancement

#44 fix(homepage): query community builder webp images
  apps/web/src/components/JoinTheCommunity/JoinTheCommunity.tsx
Labels: type: bug

#45 Remove cbhq URL from CSP
  apps/base-docs/server.js
  apps/web/next.config.js
Labels: minor

#46 Remove package-lock, we use yarn
  .gitignore
  package-lock.json
Labels: minor, type: bug

#40 Add Stackup to Node Providers page
  apps/base-docs/docs/tools/node-providers.md
Labels: type: enhancement

#48 chore(bootcamp): replace backtick with apostrophe
  apps/web/src/components/Bootcamp/WhatsIncluded.tsx
Labels: minor, type: bug

#49 fix(doc search): Refactor search box for optimal display on handheld devices
  apps/base-docs/src/theme/SearchBar.jsx
  apps/base-docs/src/theme/kbar.module.css
Labels: minor, type: bug

#60 update-node-providers-add-1rpc-base-support
  apps/base-docs/docs/tools/node-providers.md
Labels: state: backlog, type: enhancement

#67 Add Algolia indexer Github Action and config.
  .github/workflows/update-algolia.yml
  apps/base-docs/algolia.json
Labels: type: enhancement

#74 Algolia Docs Search
  apps/base-docs/docusaurus.config.js
  apps/base-docs/package.json
  apps/base-docs/server.js
  apps/base-docs/src/css/custom.css
  apps/base-docs/src/plugins/docusaurus-plugin-kbar/getKBarActions.js
  apps/base-docs/src/plugins/docusaurus-plugin-kbar/index.js
  apps/base-docs/src/plugins/docusaurus-plugin-kbar/kbar.js
  apps/base-docs/src/plugins/docusaurus-plugin-kbar/logger.js
  apps/base-docs/src/theme/KBarAnimator.jsx
  apps/base-docs/src/theme/KBarPortal.jsx
  apps/base-docs/src/theme/KBarResults.jsx
  apps/base-docs/src/theme/KBarSearch.jsx
  apps/base-docs/src/theme/Layout/Provider/index.jsx
  apps/base-docs/src/theme/SearchBar.jsx
  apps/base-docs/src/theme/kbar.module.css
  apps/base-docs/src/theme/useKBarPluginData.js
  yarn.lock
Labels: state: in progress, type: enhancement

#75 Add LearnWeb3 faucet to list
  apps/base-docs/docs/tools/network-faucets.md
Labels: type: enhancement

#85 docs(bridge): Add additional FAQs
  apps/base-docs/docs/tools/bridge-faq.md
  apps/bridge/src/components/Faq/FaqSidebar.tsx
Labels: type: enhancement

#80 docs: update "run a base node" instructions
  apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
Labels: type: enhancement, type: question

#79 feat: add flair indexing
  apps/base-docs/docs/tools/data-indexers.md
Labels: type: enhancement, type: question
