Repository base/web, pull requests merged in 2023-12, with the labels that each got.

#170 Update mappings-sbs and basic-types
  apps/base-docs/base-camp/docs/contracts-and-basic-functions/basic-types.md
  apps/base-docs/base-camp/docs/mappings/mappings-sbs.md
Labels: state: in progress

#167 Update onboarding.md
  apps/base-docs/docs/tools/onboarding.md
Labels: state: in progress

#174 update error-triage, simple-storage & new-keyword
  apps/base-docs/base-camp/docs/error-triage/error-triage.md
  apps/base-docs/base-camp/docs/new-keyword/new-keyword-exercise.md
  apps/base-docs/base-camp/docs/new-keyword/new-keyword-sbs.md
  apps/base-docs/base-camp/docs/storage/simple-storage-sbs.md
Labels: state: in progress

#157 feat: add wstETH on Base
  apps/bridge/assets.ts
  apps/bridge/public/icons/currency/wsteth.svg
Labels: state: backlog

#177 Update structs-exercise.md Data type warning
  apps/base-docs/base-camp/docs/structs/structs-exercise.md
Labels: state: backlog

#166 Includes Particle Network within onboarding.md
  apps/base-docs/docs/tools/onboarding.md
Labels: state: backlog

#162 Content for Frontend Setup in Base Camp
  apps/base-docs/base-camp/assets/images/reading-and-displaying-data/issues-console-log.png
  apps/base-docs/base-camp/assets/images/reading-and-displaying-data/missing-data.png
  apps/base-docs/base-camp/docs/frontend-setup/building-an-onchain-app.md
  apps/base-docs/base-camp/docs/frontend-setup/wallet-connectors.md
  apps/base-docs/base-camp/docs/reading-and-displaying-data/configuring-useContractRead.md
  apps/base-docs/base-camp/docs/reading-and-displaying-data/useAccount.md
  apps/base-docs/base-camp/docs/reading-and-displaying-data/useContractRead.md
  apps/base-docs/base-camp/docs/writing-to-contracts/useContractWrite.md
  apps/base-docs/base-camp/docs/writing-to-contracts/usePrepareContractWrite.md
  apps/base-docs/base-camp/sidebars.js
Labels: state: in progress

#204 updated Supra information in oracles.md
  apps/base-docs/docs/tools/oracles.md
Labels: type: docs

#179 Neo/write foundry deployment guide
  apps/base-docs/docs/building-with-base/guides/deploy-smart-contracts.mdx
  apps/base-docs/docs/building-with-base/guides/deploy-with-foundry.md
  apps/base-docs/sidebars.js
Labels: state: backlog

#183 Introduction and testing with Foundry guides
  apps/base-docs/docs/building-with-base-and-foundry/introduction.md
  apps/base-docs/docs/building-with-base-and-foundry/testing.md
Labels: state: in progress
