Repository base/web, pull requests merged in 2024-06, with the labels that each got.

#544 Update Coinbase Onramp getting started link
  apps/base-docs/docs/tools/onramps.md
Labels: type: docs

#546 feat(ecosystem): New additions to Ecosystem page
  apps/web/public/images/partners/center-logo.png
  apps/web/public/images/partners/droplinked.png
  apps/web/public/images/partners/dyson-money.png
  apps/web/public/images/partners/galaxy-exchange.png
  apps/web/public/images/partners/here-wallet.jpeg
  apps/web/public/images/partners/quill-audits.png
  apps/web/public/images/partners/robots-farm.png
  apps/web/public/images/partners/tegro.jpg
  apps/web/public/images/partners/vooi.png
  apps/web/src/data/ecosystem.json
Labels: state: in progress

#522 Add RockX to node providers
  apps/base-docs/docs/tools/node-providers.md
Labels: state: in progress

#523 New guide (tutorial): Build a Dynamic NFT on Base with Irys
  apps/base-docs/assets/images/dynamic-nfts/NFT_level_1.png
  apps/base-docs/assets/images/dynamic-nfts/NFT_level_2.png
  apps/base-docs/assets/images/dynamic-nfts/NFT_level_3.png
  apps/base-docs/assets/images/dynamic-nfts/all-characters.png
  apps/base-docs/assets/images/dynamic-nfts/base-dynamic-nft.zip
  apps/base-docs/assets/images/dynamic-nfts/image-level-1.png
  apps/base-docs/assets/images/dynamic-nfts/image-level-2.png
  apps/base-docs/assets/images/dynamic-nfts/image-level-3.png
  apps/base-docs/assets/images/dynamic-nfts/mutable-references.png
  apps/base-docs/assets/images/dynamic-nfts/open-sea-mockup.jpg
  apps/base-docs/assets/images/dynamic-nfts/refresh-metadata.png
  apps/base-docs/static/json/authors.json
  apps/base-docs/tutorials/data.json
  apps/base-docs/tutorials/docs/2_dynamic-nfts.mdx
Labels: state: in progress

#525 Update node-providers.md
  apps/base-docs/docs/tools/node-providers.md
Labels: state: in progress, change(s) requested

#538 Add API for checking proofs for multi usage
  apps/web/package.json
  apps/web/pages/api/addresses/[address]/proof/index.ts
  apps/web/src/utils/proofs.ts
  yarn.lock
Labels: state: in progress

#539 Feat: OCS registry api
  apps/web/package.json
  apps/web/pages/api/registry/entries.ts
  apps/web/pages/api/registry/featured.ts
  apps/web/src/utils/ocsRegistry.ts
  yarn.lock
Labels: state: in progress
