Repository base/web, pull requests merged in 2024-04, with the labels that each got.

#339 - Basecamp docs improved;
  apps/base-docs/base-camp/docs/advanced-functions/function-modifiers.md
  apps/base-docs/base-camp/docs/arrays/filtering-an-array-sbs.md
  apps/base-docs/base-camp/docs/erc-20-token/erc-20-token-sbs.md
  apps/base-docs/base-camp/docs/erc-721-token/erc-721-sbs.md
  apps/base-docs/base-camp/docs/error-triage/error-triage.md
  apps/base-docs/base-camp/docs/hardhat-testing/hardhat-testing-sbs.md
  apps/base-docs/base-camp/docs/imports/imports-sbs.md
  apps/base-docs/base-camp/docs/inheritance/abstract-contracts-sbs.md
  apps/base-docs/base-camp/docs/inheritance/inheritance-sbs.md
  apps/base-docs/base-camp/docs/inheritance/multiple-inheritance.md
  apps/base-docs/base-camp/docs/mappings/mappings-sbs.md
  apps/base-docs/base-camp/docs/minimal-tokens/minimal-token-sbs.md
  apps/base-docs/base-camp/docs/new-keyword/new-keyword-sbs.md
  apps/base-docs/base-camp/docs/reading-and-displaying-data/useAccount.md
  apps/base-docs/base-camp/docs/storage/simple-storage-sbs.md
  apps/base-docs/base-camp/docs/structs/structs-sbs.md
Labels: state: backlog

#372 fix: Logo svg width error
  apps/bridge/src/components/Logo/Logo.tsx
  apps/web/src/components/Logo/Logo.tsx
Labels: state: backlog

#362 Added SubQuery and OnFinality
  apps/base-docs/docs/tools/node-providers.md
Labels: state: backlog

#320 Add Particle Network AA Guide
  apps/base-docs/tutorials/docs/2_account-abstraction-with-particle-network.md
  apps/base-docs/tutorials/sidebars.js
Labels: state: backlog

#432 Update broken Avatars
  apps/web/public/images/avatars/amhed.eth.png
  apps/web/public/images/avatars/lsr.eth.png
  apps/web/src/components/CoreContributors/CoreContributors.json
Labels: state: in progress, type: bug

#466 docs(frame-transactions): Drop warning regarding no support for testnet
  apps/base-docs/tutorials/docs/3_farcaster-frames-transactions.md
Labels: state: in progress
