Repository base/web, pull requests merged in 2024-11, with the labels that each got.

#1140 Enhancements: Add comments in tos.ts and switch Twitter icon to X
  apps/bridge/pages/api/tos.ts
  apps/web/src/utils/socialPlatforms.ts
  libs/base-ui/Icon/index.tsx
Labels: state: in progress, change(s) requested, community contribution

#1224 chore: add stats page w/ datadog iframe
  apps/web/app/(stats)/layout.tsx
  apps/web/app/(stats)/stats/page.tsx
  apps/web/next.config.js
Labels: state: in progress, type: enhancement

#1225 docs(tutorial): Create tutorials for Paymaster/Wagmi + OCK Theme component
  apps/base-docs/assets/images/onchainkit-tutorials/swapped-theme-before.png
  apps/base-docs/assets/images/onchainkit-tutorials/swapped-theme-final.png
  apps/base-docs/assets/images/paymaster-tutorials/connect-wallet-mint-page.png
  apps/base-docs/assets/images/paymaster-tutorials/sponsored_mint_nft.png
  apps/base-docs/assets/images/paymaster-tutorials/wallet-home.png
  apps/base-docs/assets/images/paymaster-tutorials/wallet-nft-page.png
  apps/base-docs/tutorials/docs/1_ock-swap-theme.md
  apps/base-docs/tutorials/docs/2_ock-fund-tutorial.md
  apps/base-docs/tutorials/docs/2_paymaster-sponsor-using-wagi.md
Labels: state: in progress, type: docs
