Repository base/web, pull requests merged in 2024-01, with the labels that each got.

#218 Add support for Sepolia testnet in documentation
  apps/base-docs/docs/tools/hardhat.md
Labels: state: backlog

#220 Add BTRST to bridge UI
  apps/bridge/assets.ts
  apps/bridge/public/icons/currency/btrst.svg
Labels: state: backlog

#248 Update LearnWeb3's faucet link to point to Base Sepolia
  apps/base-docs/docs/tools/network-faucets.md
Labels: state: backlog, type: question

#235 Adding Crossmint as one of the tools helping with Onboarding, NFT Checkouts and Cross-chain payments on the Base Network
  apps/base-docs/docs/tools/cross-chain.md
  apps/base-docs/docs/tools/nft-checkout.md
  apps/base-docs/docs/tools/onboarding.md
Labels: state: backlog

#247 Add WalletKit to onboarding and AA docs
  apps/base-docs/docs/tools/account-abstraction.md
  apps/base-docs/docs/tools/onboarding.md
Labels: state: backlog

#275 Address payable
  apps/base-docs/base-camp/docs/address-and-payable/address-and-payable.md
  apps/base-docs/base-camp/sidebars.js
Labels: state: backlog, type: docs

#281 Add building onchain nft
  apps/base-docs/assets/images/onchain-generative-nfts/architecture.png
  apps/base-docs/assets/images/onchain-generative-nfts/first_pass.png
  apps/base-docs/assets/images/onchain-generative-nfts/mockup.png
  apps/base-docs/assets/images/onchain-generative-nfts/progress.png
  apps/base-docs/docs/building-with-base/guides/onchain-generative-nfts.md
Labels: state: in progress

#234 Remove reference to Base Goerli from docs
  apps/base-docs/docs/building-with-base/base-contracts.md
  apps/base-docs/docs/building-with-base/guides/run-a-base-node.md
  apps/base-docs/docs/building-with-base/network-information.md
  apps/base-docs/docs/contracts.md
  apps/base-docs/docs/tools/block-explorers.md
  apps/base-docs/docs/tools/bridges-testnet.md
  apps/base-docs/docs/tools/cross-chain.md
  apps/base-docs/docs/tools/data-indexers.md
  apps/base-docs/docs/tools/network-faucets.md
  apps/base-docs/docs/tools/node-providers.md
  apps/base-docs/docs/tools/oracles.md
  apps/base-docs/docs/using-base.md
Labels: type: docs
